apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovauth-chart.name" . }}-jwt
  annotations:
    "helm.sh/hook": "pre-install,pre-rollback"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "ovauth-chart.labels" . | nindent 4 }}
type: Opaque
data:
  jwt_shared_secret: {{ randAlphaNum 24 | b64enc }}
---
{{- if .Values.oauth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovauth-chart.name" . }}-oauth
  labels:
    {{- include "ovauth-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  app_secret: {{ .Values.oauth.appSecret }}
{{- end }}