apiVersion: v1
kind: Service
metadata:
  name: ovauth
  labels:
    {{- include "ovauth-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      name: ovauth
  selector:
    {{- include "ovauth-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ovauth-www
  labels:
    {{- include "ovauth-chart.dashboardLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: ovauth-www
  selector:
    {{- include "ovauth-chart.selectorDashboardLabels" . | nindent 4 }}